hypertrace/hypertrace-ingester

- .github/workflows/docker-tests.yml
- .github/workflows/hypertrace-ingester/docker-compose-zipkin-example.yml
- .github/workflows/hypertrace-ingester/docker-compose.yml
- .github/workflows/hypertrace-ingester/scripts/inspect.sh
- .github/workflows/hypertrace-ingester/scripts/tests.sh
This PR,
- will add quick e2e test for hypertrace-ingester which will 
- Build image on each new PR and push to main branch
- test if we are able to get full stack up and running
- generate and retrieve trace.
> adds e2e CI test for hypertrace-ingester

- raw-spans-grouper/LICENSE
- raw-spans-grouper/build.gradle.kts
- span-normalizer/LICENSE
- span-normalizer/build.gradle.kts
- span-normalizer/span-normalizer-api/build.gradle.kts
Redo of https://github.com/hypertrace/hypertrace-ingester/pull/24 as in https://github.com/hypertrace/hypertrace-ingester/pull/29
> Updates the license file of span-normalizer and raw-spans-grouper

- .circleci/config.yml
- .circleci/helm.sh
Redo of https://github.com/hypertrace/hypertrace-ingester/pull/25 as per in https://github.com/hypertrace/hypertrace-ingester/pull/29
> Fixing publish workflow 2

- hypertrace-view-generator/hypertrace-view-creator/build.gradle.kts
This PR address https://snyk.io/vuln/SNYK-JAVA-ORGAPACHECALCITE-1038296
> Fixed snyk failure for calcite-core

- hypertrace-view-generator/hypertrace-view-generator/build.gradle.kts
- hypertrace-view-generator/hypertrace-view-generator/src/main/java/org/hypertrace/viewgenerator/generators/SpanEventViewGenerator.java
Re-porting PR (https://github.com/hypertrace/hypertrace-view-generator/pull/31/) after the consolidation of repos #15
> Reporting fix before consolidation of repos

- raw-spans-grouper/helm/templates/raw-spans-grouper-config.yaml
- raw-spans-grouper/helm/values.yaml
cacheMaxBytesBuffering for cacheMaxBytesBuffering : default value 10 mb making it 16 mb
make standbyreplicas default as 0 , existing 1 . To reduce unnecessary overhead. Can be set per env if needed.
> template for cacheMaxBytesBuffering

- hypertrace-ingester/build.gradle.kts
- hypertrace-trace-enricher/enriched-span-constants/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher-api/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher/build.gradle.kts
- hypertrace-trace-enricher/trace-reader/build.gradle.kts
- hypertrace-view-generator/hypertrace-view-creator/build.gradle.kts
- hypertrace-view-generator/hypertrace-view-generator/build.gradle.kts
- raw-spans-grouper/raw-spans-grouper/build.gradle.kts
- span-normalizer/span-normalizer-constants/build.gradle.kts
- span-normalizer/span-normalizer/build.gradle.kts
We are a bit behind and were using a pre-1.0 lib
> Updates junit and log4j related dependencies

- raw-spans-grouper/helm/templates/raw-spans-grouper-config.yaml
- raw-spans-grouper/helm/values.yaml
templatise linger ms, batch size, commit interval
> templatise linger ms, batch size, commit interval

- semantic-convention-utils/build.gradle.kts
Reverts hypertrace/hypertrace-ingester#61
> Do not publish artifacts for semantic-convention-module

- semantic-convention-utils/build.gradle.kts
- semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/db/DbSemanticConventionUtils.java
- semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/error/ErrorSemanticConventionUtils.java
- semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/http/HttpSemanticConventionUtils.java
- semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/rpc/OTelRpcSemanticConventions.java
- semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/rpc/RpcSemanticConventionUtils.java
- semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/span/SpanSemanticConventionUtils.java
- span-normalizer/span-normalizer/build.gradle.kts
- span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/fieldgenerators/FieldsGenerator.java
- span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/fieldgenerators/GrpcFieldsGenerator.java
- span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/fieldgenerators/HttpFieldsGenerator.java
- span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/fieldgenerators/SqlFieldsGenerator.java
- span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanNormalizer.java
- span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/fieldgenerators/FieldsGeneratorTest.java
- span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/fieldgenerators/GrpcFieldsGeneratorTest.java
- span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/fieldgenerators/HttpFieldsGeneratorTest.java
- span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/fieldgenerators/SqlFieldsGeneratorTest.java
This pr combines all the changes done for span-normalizer for supporting OTel semantics
https://github.com/hypertrace/hypertrace-ingester/pull/69 
https://github.com/hypertrace/hypertrace-ingester/pull/65
This pr also address review comment from the above prs. 
In the subsequent pr, I will make sure we use the terminology `URL` consistently instead of `URI`
Parent issue:  hypertrace/span-normalizer#35
> OTel Semantics: Span Normalizer

- hypertrace-ingester/helm/templates/_helpers.tpl
- hypertrace-ingester/helm/templates/deployment.yaml
- hypertrace-ingester/helm/values.yaml
- hypertrace-trace-enricher/helm/templates/_helpers.tpl
- hypertrace-trace-enricher/helm/templates/deployment.yaml
- hypertrace-trace-enricher/helm/values.yaml
- hypertrace-view-generator/helm/templates/_helpers.tpl
- hypertrace-view-generator/helm/templates/all-views/all-views-creation.yaml
- hypertrace-view-generator/helm/templates/all-views/all-views-generation.yaml
- hypertrace-view-generator/helm/templates/backend-entity-view/backend-entity-view-creation.yaml
- hypertrace-view-generator/helm/templates/backend-entity-view/backend-entity-view-generation.yaml
- hypertrace-view-generator/helm/templates/raw-service-view/raw-service-view-creation.yaml
- hypertrace-view-generator/helm/templates/raw-service-view/raw-service-view-generation.yaml
- hypertrace-view-generator/helm/templates/raw-trace-view/raw-trace-view-creation.yaml
- hypertrace-view-generator/helm/templates/raw-trace-view/raw-trace-view-generation.yaml
- hypertrace-view-generator/helm/templates/service-call-view/service-call-view-creation.yaml
- hypertrace-view-generator/helm/templates/service-call-view/service-call-view-generation.yaml
- hypertrace-view-generator/helm/templates/span-event-view/span-event-view-creation.yaml
- hypertrace-view-generator/helm/templates/span-event-view/span-event-view-generation.yaml
- hypertrace-view-generator/helm/values.yaml
- raw-spans-grouper/helm/templates/_helpers.tpl
- raw-spans-grouper/helm/templates/statefulset.yaml
- raw-spans-grouper/helm/values.yaml
- span-normalizer/helm/templates/_helpers.tpl
- span-normalizer/helm/templates/deployment.yaml
- span-normalizer/helm/values.yaml
addresses https://github.com/hypertrace/hypertrace/issues/55
based on: https://github.com/hypertrace/pinot/pull/18
Tested with personal EKS cluster deployment by adding following lines in values.yaml for hypertrace deployment.
Works as expected. 
- [na] I have added tests that prove my fix is effective or that my feature works
> allows tagOverride for helm charts

- .github/workflows/pr-build.yml
- .github/workflows/publish.yml
This fixes helm package step, by updating to a new package image which supports GHA.
> fix: helm-gcs-image to handle gs

- hypertrace-trace-enricher/enriched-span-constants/src/main/java/org/hypertrace/traceenricher/enrichedspan/constants/utils/EnrichedSpanUtils.java
- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/HttpAttributeEnricher.java
- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/HttpAttributeEnricherTest.java
This fixes issue https://github.com/hypertrace/hypertrace-ingester/issues/111
> fix: Fix HttpAttributeEnricher to work with path/query string and not full url

- hypertrace-trace-enricher/hypertrace-trace-enricher-api/src/main/java/org/hypertrace/traceenricher/trace/util/ApiTraceGraph.java
- hypertrace-trace-enricher/hypertrace-trace-enricher-api/src/test/java/org/hypertrace/traceenricher/trace/util/ApiTraceGraphDebug.java
- hypertrace-trace-enricher/hypertrace-trace-enricher-api/src/test/java/org/hypertrace/traceenricher/trace/util/ApiTraceGraphTest.java
- hypertrace-view-generator/hypertrace-view-generator/src/main/java/org/hypertrace/viewgenerator/generators/RawServiceViewGenerator.java
- hypertrace-view-generator/hypertrace-view-generator/src/main/java/org/hypertrace/viewgenerator/generators/ServiceCallViewGenerator.java
- hypertrace-view-generator/hypertrace-view-generator/src/main/java/org/hypertrace/viewgenerator/generators/SpanEventViewGenerator.java
- hypertrace-view-generator/hypertrace-view-generator/src/main/java/org/hypertrace/viewgenerator/generators/ViewGeneratorState.java
- hypertrace-view-generator/hypertrace-view-generator/src/test/java/org/hypertrace/viewgenerator/generators/ServiceCallViewGeneratorTest.java
- hypertrace-view-generator/hypertrace-view-generator/src/test/java/org/hypertrace/viewgenerator/generators/SpanEventViewGeneratorTest.java
> refactor: Api trace graph Restructuring

- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/resolver/backend/JdbcBackendResolver.java
- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/resolver/backend/RabbitMqBackendResolver.java
- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/resolver/backend/RedisBackendResolver.java
- semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/db/DbSemanticConventionUtils.java
- semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/messaging/MessagingSemanticConventionUtils.java
-  handles case of statement or query being null in backend_operation to avoid null pointer exception in that case. 
NA
> chore: handles case of statement or query being null in backend_operation

- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/resolver/backend/RabbitMqBackendResolver.java
- semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/db/DbSemanticConventionUtils.java
- semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/messaging/MessagingSemanticConventionUtils.java
- semantic-convention-utils/src/test/java/org/hypertrace/semantic/convention/utils/db/DbSemanticConventionUtilsTest.java
- semantic-convention-utils/src/test/java/org/hypertrace/semantic/convention/utils/messaging/MessagingSemanticConventionUtilsTest.java
- semantic-convention-utils/src/test/java/org/hypertrace/semantic/convention/utils/messaging/OtelMessagingSemanticConventionUtilsTest.java
- semantic-convention-utils/src/test/java/org/hypertrace/semantic/convention/utils/rpc/RpcSemanticConventionUtilsTest.java
- span-normalizer/span-normalizer-constants/src/main/java/org/hypertrace/core/semantic/convention/constants/rpc/OTelRpcSemanticConventions.java
- Unit tests for updated semantic utils. 
Checked.
> test: adds unit tests for semantic utils

- hypertrace-trace-enricher/helm/templates/trace-enricher-config.yaml
There was a change in config structure, incorporating it in helm
> fix: updates helm overridden config to match with application.conf

- hypertrace-ingester/build.gradle.kts
- hypertrace-trace-enricher/enriched-span-constants/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher-api/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/processor/StructuredTracesEnrichmentTest.java
- hypertrace-trace-enricher/hypertrace-trace-enricher/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-visualizer/build.gradle.kts
- hypertrace-trace-enricher/trace-reader/build.gradle.kts
- hypertrace-view-generator/hypertrace-view-generator/build.gradle.kts
- raw-spans-grouper/raw-spans-grouper/build.gradle.kts
- semantic-convention-utils/build.gradle.kts
- span-normalizer/span-normalizer/build.gradle.kts
- span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerResourceNormalizer.java
- span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanNormalizer.java
- span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/jaeger/JaegerResourceNormalizerTest.java
Added implementation of resource ingestion. Details on change in https://github.com/hypertrace/data-model/pull/16
Added UT, verified existing UT, ran E2E and verified ingestion
> feat: add resource ingestion

- .snyk
- build.gradle.kts
- hypertrace-ingester/build.gradle.kts
- hypertrace-trace-enricher/enriched-span-constants/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher-api/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher/src/main/resources/configs/common/application.conf
- hypertrace-trace-enricher/hypertrace-trace-visualizer/build.gradle.kts
- hypertrace-trace-enricher/trace-reader/build.gradle.kts
- hypertrace-view-generator/hypertrace-view-creator/build.gradle.kts
- hypertrace-view-generator/hypertrace-view-generator/build.gradle.kts
- raw-spans-grouper/raw-spans-grouper/build.gradle.kts
- semantic-convention-utils/build.gradle.kts
- settings.gradle.kts
- span-normalizer/raw-span-constants/build.gradle.kts
- span-normalizer/span-normalizer-api/build.gradle.kts
- span-normalizer/span-normalizer-constants/build.gradle.kts
- span-normalizer/span-normalizer/build.gradle.kts
Update dependencies to clean up vulnerabilities
> chore: update dependencies

- hypertrace-ingester/build.gradle.kts
- hypertrace-view-generator/hypertrace-view-creator/build.gradle.kts
- hypertrace-view-generator/hypertrace-view-generator/build.gradle.kts
- updates version of view generator framework
> chore: updates view generator framework

- .github/workflows/docker-tests.yml
Currently the name of the e2e test are identical https://github.com/hypertrace/hypertrace-ingester/runs/2516535321?check_suite_focus=true
> fix: Update docker-tests.yml

- raw-spans-grouper/helm/templates/raw-spans-grouper-config.yaml
- raw-spans-grouper/helm/values.yaml
- raw-spans-grouper/raw-spans-grouper/src/main/java/org/hypertrace/core/rawspansgrouper/RawSpanGrouperConstants.java
- raw-spans-grouper/raw-spans-grouper/src/main/java/org/hypertrace/core/rawspansgrouper/RawSpansGrouper.java
- raw-spans-grouper/raw-spans-grouper/src/main/resources/configs/common/application.conf
- raw-spans-grouper/raw-spans-grouper/src/test/java/org/hypertrace/core/rawspansgrouper/RawSpansGrouperTest.java
> chore: Caching option for window store

- hypertrace-view-generator/hypertrace-view-generator/src/main/java/org/hypertrace/viewgenerator/generators/LogEventViewGenerator.java
- hypertrace-view-generator/hypertrace-view-generator/src/test/java/org/hypertrace/viewgenerator/generators/LogEventViewGeneratorTest.java
https://github.com/hypertrace/hypertrace/issues/224 
Update log summary
> chore: Update log summary

- raw-spans-grouper/helm/values.yaml
> chore: Update write.buffer.ratio

- semantic-convention-utils/build.gradle.kts
> publish semantic-convention-utils

- hypertrace-trace-enricher/enriched-span-constants/src/main/java/org/hypertrace/traceenricher/enrichedspan/constants/utils/EnrichedSpanUtils.java
- hypertrace-trace-enricher/enriched-span-constants/src/test/java/org/hypertrace/traceenricher/enrichedspan/constants/utils/EnrichedSpanUtilsTest.java
> Fix http uri

- hypertrace-view-generator/hypertrace-view-generator/src/test/java/org/hypertrace/viewgenerator/generators/BackendEntityViewGeneratorTest.java
- hypertrace-view-generator/hypertrace-view-generator/src/test/java/org/hypertrace/viewgenerator/generators/RawTraceViewGeneratorTest.java
- hypertrace-view-generator/hypertrace-view-generator/src/test/java/org/hypertrace/viewgenerator/generators/ServiceCallViewGeneratorTest.java
- hypertrace-view-generator/hypertrace-view-generator/src/test/java/org/hypertrace/viewgenerator/generators/TestUtilities.java
Added unit test for Backend Entity View Generation class
Not necessary as unit test addition.
> adding backendEntityViewGenerator Test

- semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/http/HttpSemanticConventionUtils.java
- semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/rpc/RpcSemanticConventionUtils.java
> changes for trace enricher

- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher/build.gradle.kts
- semantic-convention-utils/build.gradle.kts
Changed entity-service version
No tests needed
> New version of entity-service-client

- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/EnrichmentProcessor.java
Log exception stacktrace during enrichment process
> Log exception stacktrace during enrichment

- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/backend/AbstractBackendEntityEnricher.java
Small refactor to support better extension of backend enrichment 
Relying on existing tests
> refactor: move code around for backend service check

- hypertrace-trace-enricher/enriched-span-constants/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher/build.gradle.kts
- hypertrace-trace-enricher/trace-reader/build.gradle.kts
- hypertrace-view-generator/hypertrace-view-generator/build.gradle.kts
- semantic-convention-utils/build.gradle.kts
Updating entity libs for entity caching client concurrency fix.
Source https://github.com/hypertrace/entity-service/pull/112 and https://github.com/hypertrace/entity-service/pull/114
> chore: update entity libs

- hypertrace-trace-enricher/helm/Chart.yaml
- hypertrace-trace-enricher/helm/values.yaml
- hypertrace-view-generator/helm/Chart.yaml
- hypertrace-view-generator/helm/values.yaml
- raw-spans-grouper/helm/Chart.yaml
- raw-spans-grouper/helm/values.yaml
- span-normalizer/helm/Chart.yaml
- span-normalizer/helm/values.yaml
Kafka topic structure changed from list to map in helm charts
Changed retention duration to 1 day, max message bytes for sessions/traces.
> Kafka Topic Config Change

- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/cache/EntityCache.java
- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/space/SpaceRulesCachingClient.java
Enabled reporting guava cache stats
> Enabled guava cache stats metric reporting

- span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanPreProcessor.java
- span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/SpanFilter.java
> log dropped spans in rate limited manner

- .snyk
- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/clients/DefaultClientRegistry.java
Use common channel registry to build and manage channels centrally.
> refactor: use channel registry

- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/clients/DefaultClientRegistry.java
Config to control the write throttling duration
> Ability to configure the write throttling via config

- hypertrace-view-generator/hypertrace-view-generator-api/src/main/avro/SpanEventView.avdl
Changed spans default value to 1.
> fix : updated default value

- hypertrace-ingester/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher/build.gradle.kts
- hypertrace-trace-enricher/trace-reader/build.gradle.kts
- hypertrace-view-generator/hypertrace-view-creator/build.gradle.kts
- hypertrace-view-generator/hypertrace-view-generator/build.gradle.kts
- raw-spans-grouper/raw-spans-grouper/build.gradle.kts
- span-normalizer/span-normalizer/build.gradle.kts
> fix: update log4j

- .snyk
- build.gradle.kts
- hypertrace-metrics-exporter/hypertrace-metrics-exporter/build.gradle.kts
- hypertrace-metrics-generator/hypertrace-metrics-generator-api/build.gradle.kts
- hypertrace-metrics-generator/hypertrace-metrics-generator/build.gradle.kts
- hypertrace-metrics-processor/hypertrace-metrics-processor/build.gradle.kts
- hypertrace-trace-enricher/enriched-span-constants/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher-api/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher/build.gradle.kts
- hypertrace-trace-enricher/trace-reader/build.gradle.kts
- hypertrace-view-generator/hypertrace-view-creator/build.gradle.kts
- hypertrace-view-generator/hypertrace-view-generator/build.gradle.kts
- raw-spans-grouper/raw-spans-grouper/build.gradle.kts
- semantic-convention-utils/build.gradle.kts
- span-normalizer/raw-span-constants/build.gradle.kts
- span-normalizer/span-normalizer-api/build.gradle.kts
- span-normalizer/span-normalizer/build.gradle.kts
Update docker plugin for M1 support as described in https://github.com/hypertrace/hypertrace-gradle-docker-plugins/pull/29
Build issue, tested on local x86 and on contributor's M1 machine.
> chore: upgrade docker plugin for m1 support

- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/EnrichmentProcessor.java
In the previous PR - https://github.com/hypertrace/hypertrace-ingester/pull/329 - I had a catch throwable that would have stuff OOM and other errors. So, as part of this, I added a specific error exception.
> fix: handle explicit error case

- hypertrace-ingester/build.gradle.kts
- hypertrace-metrics-exporter/hypertrace-metrics-exporter/build.gradle.kts
- hypertrace-metrics-generator/hypertrace-metrics-generator/build.gradle.kts
- hypertrace-metrics-processor/hypertrace-metrics-processor/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher/build.gradle.kts
- hypertrace-view-generator/hypertrace-view-generator/build.gradle.kts
- raw-spans-grouper/raw-spans-grouper/build.gradle.kts
- span-normalizer/span-normalizer-api/build.gradle.kts
- span-normalizer/span-normalizer/build.gradle.kts
Update versions to fix vulnerabilities
> Upgrade dependencies to fix vulnerabilities

- semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/http/HttpSemanticConventionUtils.java
- semantic-convention-utils/src/test/java/org/hypertrace/semantic/convention/utils/http/HttpSemanticConventionUtilsTest.java
> handle "null" string case for the http request origin header

- build.gradle.kts
- hypertrace-ingester/build.gradle.kts
- hypertrace-metrics-exporter/hypertrace-metrics-exporter/build.gradle.kts
- hypertrace-metrics-generator/hypertrace-metrics-generator/build.gradle.kts
- hypertrace-metrics-processor/hypertrace-metrics-processor/build.gradle.kts
- hypertrace-view-generator/hypertrace-view-creator/build.gradle.kts
- hypertrace-view-generator/hypertrace-view-generator-api/build.gradle.kts
- raw-spans-grouper/raw-spans-grouper/build.gradle.kts
- raw-spans-grouper/raw-spans-grouper/src/main/java/org/hypertrace/core/rawspansgrouper/TraceEmitPunctuator.java
- semantic-convention-utils/build.gradle.kts
- semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/db/DbSemanticConventionUtils.java
- semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/http/HttpSemanticConventionUtils.java
- semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/rpc/RpcSemanticConventionUtils.java
- span-normalizer/span-normalizer-api/build.gradle.kts
gradle plugin upgrades and spotless fixes
NA
NA
> gradle plugin upgrades and spotless fixes

- hypertrace-ingester/build.gradle.kts
- hypertrace-metrics-exporter/hypertrace-metrics-exporter/build.gradle.kts
- hypertrace-metrics-generator/hypertrace-metrics-generator-api/build.gradle.kts
- hypertrace-metrics-generator/hypertrace-metrics-generator/build.gradle.kts
- hypertrace-metrics-processor/hypertrace-metrics-processor/build.gradle.kts
- hypertrace-trace-enricher/enriched-span-constants/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher-api/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher/build.gradle.kts
- hypertrace-trace-enricher/trace-reader/build.gradle.kts
- hypertrace-view-generator/hypertrace-view-creator/build.gradle.kts
- hypertrace-view-generator/hypertrace-view-generator-api/build.gradle.kts
- hypertrace-view-generator/hypertrace-view-generator/build.gradle.kts
- raw-spans-grouper/raw-spans-grouper/build.gradle.kts
- semantic-convention-utils/build.gradle.kts
- span-normalizer/span-normalizer-api/build.gradle.kts
- span-normalizer/span-normalizer-constants/build.gradle.kts
- span-normalizer/span-normalizer/build.gradle.kts
Kafka upgrade and TPL upgrade.
Unit testing and manual testing on sandbox environment. 
NA.
> Kafka upgrade

- hypertrace-trace-enricher/helm/templates/trace-enricher-config.yaml
- hypertrace-trace-enricher/helm/values.yaml
- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/UserAgentSpanEnricher.java
- hypertrace-trace-enricher/hypertrace-trace-enricher/src/main/resources/configs/common/application.conf
> Updated user agent cache size

- hypertrace-ingester/build.gradle.kts
- hypertrace-metrics-exporter/hypertrace-metrics-exporter/build.gradle.kts
- hypertrace-metrics-generator/hypertrace-metrics-generator/build.gradle.kts
- hypertrace-metrics-processor/hypertrace-metrics-processor/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/build.gradle.kts
- hypertrace-trace-enricher/hypertrace-trace-enricher/build.gradle.kts
- hypertrace-trace-enricher/trace-reader/build.gradle.kts
- hypertrace-view-generator/hypertrace-view-generator/build.gradle.kts
- raw-spans-grouper/raw-spans-grouper/build.gradle.kts
- span-normalizer/span-normalizer/build.gradle.kts
- span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/ExcludeSpanRuleEvaluator.java
Hypertrace libraries upgrade.
Manual testing. 
NA.
> Lib upgrade

- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/clients/ClientRegistry.java
- hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/clients/DefaultClientRegistry.java
- span-normalizer/helm/templates/span-normalizer-config.yaml
- span-normalizer/helm/values.yaml
- span-normalizer/span-normalizer/build.gradle.kts
- span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/SpanNormalizer.java
- span-normalizer/span-normalizer/src/main/resources/configs/common/application.conf
- span-normalizer/span-normalizer/src/test/resources/configs/span-normalizer/application.conf
Use group partitioner for output topics producer.
Local testing.
NA
> use group partitioner

- raw-spans-grouper/helm/values.yaml
Updated cleanup policy for change log topics. For change log topics cleanup policy should be compact, delete.
> Update change log topics compaction policy

- raw-spans-grouper/helm/values.yaml
Add replication factor and partitions
> Kafka changelog topics compact policy 2

- span-normalizer/span-normalizer/build.gradle.kts
> chore | validate the regex passed for matching

- span-normalizer/span-normalizer/build.gradle.kts
> chore | Remove exception logging from error

- span-normalizer/span-normalizer/build.gradle.kts
> chore | Validate regex before persisting

- hypertrace-trace-enricher/enriched-span-constants/src/main/java/org/hypertrace/traceenricher/enrichedspan/constants/utils/EnrichedSpanUtils.java
> Expose deployment name from EnrichedSpanUtils

- gradle/libs.versions.toml
> use v2 log4j-api and slf4j2impl

- owasp-suppressions.xml
- semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/messaging/MessagingSemanticConventionUtils.java
- span-normalizer/span-normalizer-constants/src/main/java/org/hypertrace/core/semantic/convention/constants/messaging/OtelMessagingSemanticConventions.java
> Add new otel attribute for Rabbitmq backend
