hypertrace/hypertrace-ingester

README.md
This PR
- Adds service description which explains e2e flow of `Hypertrace Ingester`
- Adds how to build and test docker image
- Adds docker image source
=> Adds Description, Testing Source and image source in README

.github/workflows/PULL_REQUEST_TEMPLATE.md
Adds PR template in `.github` folder to make PRs more informative for external developers or contributors. 
For detailed context and discussion check out: https://github.com/hypertrace/hypertrace/pull/111
=> chore: adds PR template

hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/SpanTypeAttributeEnricher.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/resolver/backend/HttpBackendResolver.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/resolver/backend/BackendEntityResolverTest.java
At some places, we're extracting fields out of HTTP URL but they are already present as first class fields. Not only we're doing extra processing, but this could be error prone as well - like we're using URI to parse the URL string field. The problem with it is that it throws an exception if there are some illegal characters in the query string. These invalid query strings can be potential security threats. However, parsing those string fields with URL object(as done by span-normalizer) works fine.
So, it is better to use the first class Http fields directly instead of extracting them out of URL.
This PR was initially raised in hypertrace-trace-enricher : hypertrace/hypertrace-trace-enricher#47 . Ported it here as hypertrace-trace-enricher has been moved inside hypertrace-ingester
=> Use first class Http fields directly instead of extracting fields out of URL

hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/resources/missing-downstream-entry-spans/after-enrichment.json, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/resources/missing-downstream-entry-spans/before-enrichment.json, span-normalizer/raw-span-constants/src/main/proto/org/hypertrace/core/span/constants/v1/span_attribute.proto, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanNormalizer.java, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/JaegerSpanNormalizerTest.java, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/SpanNormalizerTest.java
Any consumers of this attribute will now read service name from https://github.com/hypertrace/data-model/blob/main/data-model/src/main/avro/Event.avdl#L61
This attribute key will just surface in the ui under attribute list
=> Rename attribute key from jaeger.servicename to servicename 

hypertrace-trace-enricher/trace-reader/build.gradle.kts, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/attributes/AvroBackedValueSource.java, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/attributes/DefaultTraceAttributeReader.java, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/attributes/DefaultValueCoercer.java, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/attributes/DefaultValueResolver.java, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/attributes/SpanValueSource.java, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/attributes/TraceAttributeReader.java, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/attributes/TraceValueSource.java, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/attributes/ValueCoercer.java, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/attributes/ValueResolver.java, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/attributes/ValueSource.java, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/entities/AttributeValueConverter.java, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/entities/AvroEntityConverter.java, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/entities/DefaultTraceEntityReader.java, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/entities/TraceEntityReader.java, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/entities/TraceEntityReaderBuilder.java, hypertrace-trace-enricher/trace-reader/src/test/java/org/hypertrace/trace/reader/attributes/AvroUtil.java, hypertrace-trace-enricher/trace-reader/src/test/java/org/hypertrace/trace/reader/attributes/DefaultTraceAttributeReaderTest.java, hypertrace-trace-enricher/trace-reader/src/test/java/org/hypertrace/trace/reader/attributes/DefaultValueCoercerTest.java, hypertrace-trace-enricher/trace-reader/src/test/java/org/hypertrace/trace/reader/attributes/DefaultValueResolverTest.java, hypertrace-trace-enricher/trace-reader/src/test/java/org/hypertrace/trace/reader/attributes/LiteralValueUtil.java, hypertrace-trace-enricher/trace-reader/src/test/java/org/hypertrace/trace/reader/attributes/SpanValueSourceTest.java, hypertrace-trace-enricher/trace-reader/src/test/java/org/hypertrace/trace/reader/attributes/TraceValueSourceTest.java, hypertrace-trace-enricher/trace-reader/src/test/java/org/hypertrace/trace/reader/entities/AttributeValueConverterTest.java, hypertrace-trace-enricher/trace-reader/src/test/java/org/hypertrace/trace/reader/entities/AttributeValueUtil.java, hypertrace-trace-enricher/trace-reader/src/test/java/org/hypertrace/trace/reader/entities/AvroEntityConverterTest.java, hypertrace-trace-enricher/trace-reader/src/test/java/org/hypertrace/trace/reader/entities/DefaultTraceEntityReaderTest.java
The entity reader is a client library allowing reading entities from span and trace data on the fly. These will be reported back to entity service based on a caching configuration. Unlike our existing solutions for querying entities, this reader removes the responsibility of the caller to form entities in code, and instead is config driven allowing new entity types, tenant level configuration and modifying existing entity schemas without code changes.
Unit tests added. This is new functionality be tested in an integration environment before usage.
=> feat: add trace entity reader

.github/workflows/hypertrace-ingester/docker-compose.yml, .snyk, hypertrace-trace-enricher/helm/templates/trace-enricher-config.yaml, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/EntitySpanEnricher.java, hypertrace-trace-enricher/hypertrace-trace-enricher/src/main/resources/configs/common/application.conf, hypertrace-trace-enricher/trace-reader/build.gradle.kts, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/attributes/DefaultTraceAttributeReader.java, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/attributes/DefaultValueResolver.java, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/attributes/SpanValueSource.java, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/attributes/TraceValueSource.java, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/attributes/ValueSource.java, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/entities/DefaultTraceEntityReader.java
This adds the dynamic entity enricher to the enrichment pipeline, which uses the trace reader to register any entities based on configs looked up from the entity service. These definitions will be built out in time to support adding more entities via config rather than code, potentially customized to specific tenants.
=> feat: add dynamic entity enricher

.circleci/config.yml
Authenticating on pull requests complicates configuration and gives a
chance to leak credentials to those raising pull requests.
According to the below, CircleCI partnered with Docker (the company) to
eliminate the need to authenticate reads.
https://discuss.circleci.com/t/updated-authenticate-with-docker-to-avoid-impact-of-nov-1st-rate-limits/37567
See #17
=> Stops authenticating docker.io for read-access

hypertrace-trace-enricher/trace-reader/build.gradle.kts, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/entities/AttributeValueConverter.java, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/entities/DefaultTraceEntityReader.java, hypertrace-trace-enricher/trace-reader/src/test/java/org/hypertrace/trace/reader/entities/AttributeValueConverterTest.java, hypertrace-trace-enricher/trace-reader/src/test/java/org/hypertrace/trace/reader/entities/DefaultTraceEntityReaderTest.java
This change is part of the support for https://github.com/hypertrace/hypertrace/issues/126 - it adds support for entity formation when an associated attribute for an entity is missing. If the associated id or name is missing, the entity is not formed. If a regular attribute is missing, it is just omitted from the attribute map.
=> fix: omit null valued attributes rather than erroring

hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/ApiBoundaryTypeAttributeEnricher.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/ApiStatusEnricher.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/ApiBoundaryTypeAttributeEnricherTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/resolver/backend/BackendEntityResolverTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/resolver/backend/JdbcBackendResolverTest.java, hypertrace-view-generator/hypertrace-view-generator/src/main/java/org/hypertrace/viewgenerator/generators/ServiceCallViewGenerator.java, semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/db/DbSemanticConventionUtils.java, semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/span/SpanSemanticConventionUtils.java, semantic-convention-utils/src/test/java/org/hypertrace/semantic/convention/utils/db/DbSemanticConventionUtilsTest.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/fieldgenerators/FieldsGenerator.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/fieldgenerators/HttpFieldsGenerator.java, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/fieldgenerators/SqlFieldsGeneratorTest.java
Following changes has been done:
* Use first class field for http url, method in ServiceCallViewGenerator
* Do not use otel key db.connection_string for db url
* Add OTel status code in ApiStatusEnricher
* Add OTel http host key, in the list of HOST_HEADERS in ApiBoundaryType enricher
=> OTel Semantics: Some minor changes here & there

hypertrace-ingester/build.gradle.kts, hypertrace-trace-enricher/enriched-span-constants/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher-api/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/ApiBoundaryTypeAttributeEnricher.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/ApiBoundaryTypeAttributeEnricherTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-visualizer/build.gradle.kts, hypertrace-trace-enricher/trace-reader/build.gradle.kts, hypertrace-view-generator/hypertrace-view-generator-api/build.gradle.kts, hypertrace-view-generator/hypertrace-view-generator/build.gradle.kts, raw-spans-grouper/raw-spans-grouper/build.gradle.kts, semantic-convention-utils/build.gradle.kts, span-normalizer/span-normalizer-api/build.gradle.kts, span-normalizer/span-normalizer/build.gradle.kts
Due to this, the host header was being set as `:port`, which isn't right.
Fixing the bug to ignore such host header so that the span will be resolved
based on the servicename that comes in the span.
=> GRPC authority header seems to not have host component sometimes.

.github/workflows/docker-tests.yml
While trying POC on GitHub action we realised that docker 19.03 and Java 11 are part of runner that comes with Ubuntu-20.04 already has those requirements satisfied. (ref: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md)
NA
- https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
=> optimised docker e2e test with GH action

.github/workflows/hypertrace-ingester/docker-compose.yml, hypertrace-ingester/build.gradle.kts, hypertrace-view-generator/hypertrace-view-creator/build.gradle.kts, hypertrace-view-generator/hypertrace-view-generator/build.gradle.kts
For more details, see https://github.com/hypertrace/view-generator-framework/pull/23
=> chore: update view creator to fix multivalued col default

hypertrace-trace-enricher/hypertrace-trace-enricher/src/main/resources/configs/common/application.conf
While working on the issue - https://github.com/hypertrace/hypertrace/issues/128, I have observed the following topology sort for enrichers.
As we can see from the code - https://github.com/hypertrace/hypertrace-trace-enricher/blob/435d21caab170c5b8d207785204b61839089a599/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/BackendEntityEnricher.java#L112 - that backend entity enricher depended on attribute `ApiAttribute.API_ATTRIBUTE_ID` in EndpointEnricher. So, adding the dependency.
=> Correcting the dependency order for backend entity enricher

hypertrace-view-generator/hypertrace-view-generator/src/main/java/org/hypertrace/viewgenerator/generators/SpanEventViewGenerator.java, hypertrace-view-generator/hypertrace-view-generator/src/test/java/org/hypertrace/viewgenerator/generators/SpanEventViewGeneratorTest.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/fieldgenerators/HttpFieldsGenerator.java, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/fieldgenerators/HttpFieldsGeneratorTest.java
Option 2 of https://github.com/hypertrace/hypertrace-ingester/pull/99
The changes include: 
1. Update HttpFieldsGenerator#maybeSetHttpUrlForOtelFormat to overwrite relative url
2. Update the logic to fetch http url in SpanEventViewGenerator
=> Set Event.http.request.url on a best effort basis - 2

hypertrace-trace-enricher/hypertrace-trace-enricher-api/src/main/java/org/hypertrace/traceenricher/trace/util/ApiTraceGraph.java, hypertrace-view-generator/hypertrace-view-generator/src/main/java/org/hypertrace/viewgenerator/generators/BaseViewGenerator.java, hypertrace-view-generator/hypertrace-view-generator/src/main/java/org/hypertrace/viewgenerator/generators/RawServiceViewGenerator.java, hypertrace-view-generator/hypertrace-view-generator/src/main/java/org/hypertrace/viewgenerator/generators/ServiceCallViewGenerator.java, hypertrace-view-generator/hypertrace-view-generator/src/main/java/org/hypertrace/viewgenerator/generators/ViewGeneratorState.java, hypertrace-view-generator/hypertrace-view-generator/src/test/java/org/hypertrace/viewgenerator/generators/ViewGeneratorStateTest.java
Currently we run, all the view-generators in individual services. 
Although we do have a possibility of running view generator together in a single service using `MultiViewGeneratorLauncher`,
though that won't be very optimal due to repeated operations amongst the view-generators. 
This pr tries to optimise that by caching shared state in a threadlocal, thus ensuring that for a given Trace, those operations are performed once. 
Note: this changes should not affect in the case when view-generators have to be individually deployed
=> Optimisation: Share state between view-generators 

span-normalizer/helm/templates/span-normalizer-config.yaml, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanNormalizer.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanToAvroRawSpanTransformer.java, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/JaegerSpanNormalizerTest.java
This comes in handy when there is a lot of unnecessary data coming into Hypertrace platform that's not really useful for API observability.
=> feat: Adding a new feature which allows us to drop spans matching some criterion.

span-normalizer/span-normalizer-constants/src/main/java/org/hypertrace/core/semantic/convention/constants/deployment/OTelDeploymentSemanticConventions.java
Based off of:
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/deployment_environment.md
A few questions when looking in this code (@rish691 I think you have the most context):
- Why are we using enums rather that static final constants? It seems like we're either using `.getValue()` everywhere or just saving them into constants anyway like
`  private static final String OTEL_NET_PEER_IP = OTelSpanSemanticConventions.NET_PEER_IP.getValue();`
- Given that we're not actually using this in enrichment today, are there any other expected changes here? It seems like the utils around this are just wrappers for the enrichers.
=> refactor: add otel deployment env constant

hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/resolver/backend/RabbitMqBackendResolver.java, semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/messaging/MessagingSemanticConventionUtils.java, semantic-convention-utils/src/test/java/org/hypertrace/semantic/convention/utils/messaging/OtelMessagingSemanticConventionUtilsTest.java
Log warning messages in RabbitMqResolver, only when there is some identifying attribute for RabbitMq is present.
=> chore: Controlled logging in RabbitMqResolver

raw-spans-grouper/helm/templates/raw-spans-grouper-config.yaml, raw-spans-grouper/raw-spans-grouper/src/main/java/org/hypertrace/core/rawspansgrouper/RawSpanGrouperConstants.java, raw-spans-grouper/raw-spans-grouper/src/main/java/org/hypertrace/core/rawspansgrouper/RawSpansGroupingTransformer.java, raw-spans-grouper/raw-spans-grouper/src/test/java/org/hypertrace/core/rawspansgrouper/RawSpansGrouperTest.java, raw-spans-grouper/raw-spans-grouper/src/test/resources/configs/raw-spans-grouper/application.conf
Added support for optional configuration to limit the number of spans in a trace. This config can be specified at per tenant level.
```
max.span.count = {
eff27b72-622d-44d7-a0ca-1271a885a7a1 = 1000
}
```
=> Limit the number of spans in a trace

hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/BackendType.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/resolver/backend/BackendEntityResolver.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/resolver/backend/KafkaBackendResolver.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/resolver/backend/SqsBackendResolver.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/resolver/backend/KafkaBackendResolverTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/resolver/backend/SqsBackendResolverTest.java, semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/db/DbSemanticConventionUtils.java, semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/messaging/MessagingSemanticConventionUtils.java, semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/span/SpanSemanticConventionUtils.java, span-normalizer/span-normalizer-constants/src/main/java/org/hypertrace/core/semantic/convention/constants/messaging/OtelMessagingSemanticConventions.java, span-normalizer/span-normalizer-constants/src/main/java/org/hypertrace/core/semantic/convention/constants/span/OpenTracingSpanSemanticConventions.java
This PR adds support for Apache Kafka and AWS SQS to be recognised as their own backend types. 
This is one of the steps towards this issue - https://github.com/hypertrace/hypertrace/issues/169. With support for Kafka, SQS, RabbitMQ(which can be extended to other messaging systems) we can categorise the backends supported by Hypertrace into `brokers`, `storage`, etc,. to make exploring backends much easier to the user. 
Added a test case for kafka backend resolver to check if the name of the backend entity is being correctly derived from the kafka broker url. A similar test case for SQS has also been included to make sure. 
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) if …
=> feat: adding two new backend entity type and its resolver  - kafka, and sqs

hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/AbstractTraceEnricher.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/EnrichmentProcessor.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/BackendEntityEnricher.java, hypertrace-trace-enricher/hypertrace-trace-enricher/build.gradle.kts, span-normalizer/span-normalizer/build.gradle.kts
Add a catch clause to prevent crashing the entire enricher on a failed enrichment. Instead, end enrichment for that trace (as later enrichers may have depended on the failed enrichment) and proceed.
=> fix: catch errors thrown during enrichment

hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/attributes/SpanValueSource.java, hypertrace-trace-enricher/trace-reader/src/test/java/org/hypertrace/trace/reader/attributes/SpanValueSourceTest.java
Added support for reading attributes from a span-associated resource.
Added UT
=> feat: add support to trace reader to read resources

hypertrace-trace-enricher/hypertrace-trace-enricher/src/main/resources/configs/common/application.conf, hypertrace-trace-enricher/trace-reader/build.gradle.kts, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/attributes/DefaultValueResolver.java, hypertrace-trace-enricher/trace-reader/src/test/java/org/hypertrace/trace/reader/attributes/DefaultValueResolverTest.java
This is the implementation side that allows resolution of a fallback attribute definition added and described in https://github.com/hypertrace/attribute-service/pull/84
Added UT and verified functionality E2E
=> feat: add support for resolving first available attribute

hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/ErrorsAndExceptionsEnricher.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/ErrorsAndExceptionsEnricherTest.java, semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/error/ErrorSemanticConventionUtils.java, semantic-convention-utils/src/test/java/org/hypertrace/semantic/convention/utils/error/ErrorSemanticConventionUtilsTest.java, span-normalizer/span-normalizer-constants/src/main/java/org/hypertrace/core/semantic/convention/constants/error/OTelErrorSemanticConventions.java
Fixes the issue described here - https://github.com/hypertrace/hypertrace/issues/232
This is happening as we are only checking the existence of error attributes. However, as per [open tracing semantics](https://github.com/opentracing/specification/blob/master/semantic_conventions.md), span error is represented as boolean.
The PR also handles otel semantics for indicating error span using stat using status.code as `unset`, `ok`, and `error` - https://github.com/open-telemetry/opentelemetry-specification/blob/ae31114e2d441f1ecd249ce11bb924a6ac54b5d6/specification/trace/api.md#set-status
References of otel proto and collector exporter:
- https://github.com/open-telemetry/opentelemetry-proto/blob/abbf7b7b49a5342d0d6c0e86e91d713bbedb6580/opentelemetry/proto/trace/v1/trace.proto#L304
- …
=> fix: handle the semantics of error related attributes for considering error span

hypertrace-trace-enricher/enriched-span-constants/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher/build.gradle.kts, hypertrace-trace-enricher/trace-reader/build.gradle.kts, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/entities/DefaultTraceEntityReader.java, hypertrace-trace-enricher/trace-reader/src/test/java/org/hypertrace/trace/reader/entities/DefaultTraceEntityReaderTest.java, hypertrace-view-generator/hypertrace-view-generator/build.gradle.kts, semantic-convention-utils/build.gradle.kts
Entity formation previously was predicated on generating a non-null ID, but in https://github.com/hypertrace/entity-service/pull/105 support was added for defining further conditions. Here, we use that metadata to actually enforce those new conditions.
Added UTs, also verified E2E
=> feat: enforce entity formation conditions

hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/BackendEntityEnricher.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/BackendEntityEnricherTest.java
Addresses the issue - https://github.com/hypertrace/hypertrace/issues/235
This was happening after a fix of service call related - https://github.com/hypertrace/hypertrace-ingester/pull/159
Reason:
The endpoint enricher enriches all the events with API_ATTRIBUTE_ID associated with the given ApiNode. However, BackendEntityEnricher was using existence check for the same attribute to handle partial trace scenario for HTTP/GRPC backend. However, this condition is not handling the proper scenario.
Solution:
As destination API called by the client service will be associated with a service. In the case of a broken (or partial trace) scenario, we are missing links, so we are missing the entry span of the called service. And that service could be,
- identified by either HTTP BackendResolver or …
=> fix: provides a fix for handling external HTTP backends

hypertrace-trace-enricher/trace-reader/build.gradle.kts, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/attributes/DefaultValueResolver.java, hypertrace-trace-enricher/trace-reader/src/test/java/org/hypertrace/trace/reader/attributes/DefaultValueResolverTest.java
This PR does two things:
- Fixes resolution of projections and first_value_present type definitions inside a first_value_type present def
- Updates attribute projection to add support for newest operators
Added UT, verified E2E
=> fix: support projections inside first attr def

hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/entities/DefaultTraceEntityReader.java
This remote call was not propagating context and instead relying on the current thread's context - this makes it explicit.
=> fix: propagate context for building upsert

hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/resolver/backend/HttpBackendResolver.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/resolver/backend/BackendResolverTest.java, semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/http/HttpSemanticConventionUtils.java
Addresses the issue - https://github.com/hypertrace/hypertrace/issues/238
The changes use `path` as a destination from `org.hypertrace.core.datamodel.eventfields.http` instead of using only.
The `path` of `org.hypertrace.core.datamodel.eventfields.http` includes
- `http.request.path`
- `http.path`
- `http.target`
- `http.url`
References for above attributes  :  
- https://github.com/hypertrace/hypertrace-ingester/blob/main/span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/fieldgenerators/HttpFieldsGenerator.java#L94
- https://github.com/hypertrace/hypertrace-ingester/blob/main/span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/fieldgenerators/HttpFieldsGenerator.java#L275
- …
=> fix: handle the cases of resolving destination for http backend

hypertrace-ingester/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher/build.gradle.kts, hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/entities/DefaultTraceEntityReader.java, hypertrace-view-generator/hypertrace-view-generator/build.gradle.kts, raw-spans-grouper/raw-spans-grouper/build.gradle.kts, span-normalizer/span-normalizer/build.gradle.kts
Upgrading to kstream framework version to 0.1.21 to go back to kstream-6.0.1
=> chore: update kstream framework version to 0.1.21

hypertrace-trace-enricher/hypertrace-trace-enricher-api/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher-api/src/main/java/org/hypertrace/traceenricher/trace/util/ApiTraceGraph.java, hypertrace-trace-enricher/hypertrace-trace-enricher-api/src/main/java/org/hypertrace/traceenricher/trace/util/ApiTraceGraphBuilder.java, hypertrace-trace-enricher/hypertrace-trace-enricher-api/src/main/java/org/hypertrace/traceenricher/trace/util/GraphBuilderUtil.java, hypertrace-trace-enricher/hypertrace-trace-enricher-api/src/main/java/org/hypertrace/traceenricher/trace/util/StructuredTraceGraphBuilder.java, hypertrace-trace-enricher/hypertrace-trace-enricher-api/src/test/java/org/hypertrace/traceenricher/trace/util/ApiTraceGraphBuilderTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher-api/src/test/java/org/hypertrace/traceenricher/trace/util/GraphBuilderUtilTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher-api/src/test/java/org/hypertrace/traceenricher/trace/util/StructuredTraceGraphBuilderTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/ErrorsAndExceptionsEnricher.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/ExitCallsEnricher.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/endpoint/EndpointEnricher.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/ExitCallsEnricherTest.java
As part of looking into handling large traces, we have observed a couple of optimization in our ingestion pipeline as described here - https://github.com/hypertrace/hypertrace/issues/244
This PR addresses
- addresses the issue of building ApiTraceGraph across enricher for once if the trace has not modified. (Case 2 of the above ticket)
- it also modifies ApiTraceGraph internal Map data structure to use Id based index instead of using the entire object
- local testing by ingesting traces to docker-compose setup
=> fix: optimize the usage of ApiTraceGraph in the ingestion pipeline

hypertrace-view-generator/hypertrace-view-generator/src/test/java/org/hypertrace/viewgenerator/generators/RawTraceViewGeneratorTest.java
=> chore: Add unit test for view-generator service

hypertrace-trace-enricher/enriched-span-constants/build.gradle.kts, hypertrace-trace-enricher/enriched-span-constants/src/main/java/org/hypertrace/traceenricher/enrichedspan/constants/utils/EnrichedSpanUtils.java, hypertrace-trace-enricher/enriched-span-constants/src/main/proto/org/hypertrace/traceenricher/enrichedspan/constants/v1/enriched_span_attribute.proto, hypertrace-trace-enricher/enriched-span-constants/src/test/java/org/hypertrace/traceenricher/enrichedspan/constants/utils/EnrichedSpanUtilsTest.java, semantic-convention-utils/build.gradle.kts, semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/error/ErrorSemanticConventionUtils.java, semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/http/HttpSemanticConventionUtils.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/fieldgenerators/HttpFieldsGenerator.java
While retrieving http url it should also check attribute map apart from first class fields
=> Fix URI path in EnrichedSpanUtils

semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/http/HttpSemanticConventionUtils.java
As part of this PR,
- wrapped the malformed URL exception as a warning message
- refactored getHttpUrlFromRawAttributes for ease of readability
=> bug: handle the logging of malformed URL exception

hypertrace-trace-enricher/hypertrace-trace-enricher-impl/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/backend/AbstractBackendEntityEnricher.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/cache/EntityCache.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/backend/provider/CassandraBackendProviderTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/backend/provider/ClientSpanEndpointProviderTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/backend/provider/ElasticsearchBackendProviderTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/backend/provider/GrpcBackendProviderTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/backend/provider/HttpBackendProviderTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/backend/provider/JdbcBackendProviderTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/backend/provider/KafkaBackendProviderTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/backend/provider/MongoBackendProviderTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/backend/provider/RabbitMqBackendProviderTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/backend/provider/RedisBackendProviderTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/backend/provider/SqsBackendProviderTest.java, hypertrace-trace-enricher/trace-reader/build.gradle.kts
Some small refactors to make the abstract backend more extendible
UTs, sanity tested it e2e via docker compose
=> refactor: extract backend read write and identify

span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/fieldgenerators/HttpFieldsGenerator.java
- converting log level for malformed URL in a fallback case as warn and avoid printing entire stack trace
=> chore: reduce logging of error message

semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/http/HttpSemanticConventionUtils.java
Fix for following exception
```
java.lang.NullPointerException: null
at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
at java.util.Optional.<init>(Unknown Source) ~[?:?]
at java.util.Optional.of(Unknown Source) ~[?:?]
at org.hypertrace.semantic.convention.utils.http.HttpSemanticConventionUtils.getHttpRequestContentType(HttpSemanticConventionUtils.java:524) ~[semantic-convention-utils.jar:?]
```
=> bug: Fix npe in HttpSemanticConventionUtils

hypertrace-ingester/build.gradle.kts, hypertrace-trace-enricher/enriched-span-constants/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher-api/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-visualizer/build.gradle.kts, hypertrace-trace-enricher/trace-reader/build.gradle.kts, hypertrace-view-generator/hypertrace-view-generator-api/build.gradle.kts, hypertrace-view-generator/hypertrace-view-generator/build.gradle.kts, raw-spans-grouper/raw-spans-grouper/build.gradle.kts, semantic-convention-utils/build.gradle.kts, span-normalizer/span-normalizer-api/build.gradle.kts, span-normalizer/span-normalizer/build.gradle.kts
Minor transitive dependency update to fix a newly published vulnerability in commons-compress. Depends on https://github.com/hypertrace/data-model/pull/27
=> chore: update vulnerable deps

hypertrace-ingester/src/test/java/org/hypertrace/migration/MigrationTestHttp.java, hypertrace-ingester/src/test/java/org/hypertrace/migration/MigrationTestRpc.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/ApiBoundaryTypeAttributeEnricher.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanNormalizer.java
This is in the context of
-  https://github.com/hypertrace/hypertrace/issues/244
- https://github.com/hypertrace/hypertrace/issues/245
- Fixed the migration test after the change.
- all the dependent (consumer) changes to make this possible have been merged.
- we will also be removing these fields from the [data model](https://github.com/hypertrace/data-model/blob/main/data-model/src/main/avro/Event.avdl#L59) as a follow-up.
=> feat: stop populating first class event fields

hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/attributes/DefaultValueResolver.java
Excessive error construction was eating up CPU cycles - changed to lazy construction, and added a throttled log message
=> fix: change error create to be lazy

hypertrace-trace-enricher/trace-reader/build.gradle.kts
Use newer attribute client with better performing client (builds errors lazily, less exception filling)
=> chore: use newer attribute client with lazy errors

span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanPreProcessor.java
This PR adds support to emit metrics for dropped spans at tenant level.
=> emit metrics for dropped spans at tenant level

hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/UserAgentSpanEnricher.java
Optimization to avoid parsing repetitive user agent strings
=> Support for caching the parsed user agent values

span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanPreProcessor.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/SpanFilter.java
=> reduce excessive logging in case of dropped spans

hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/reader/entities/DefaultTraceEntityReader.java, hypertrace-trace-enricher/trace-reader/src/test/java/org/hypertrace/trace/reader/entities/DefaultTraceEntityReaderTest.java
Entity IDs that are present but empty strings attempt to create an invalid entity. This change filters out invalid values.
Added UTs
=> fix: filter out entities with empty ids

hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/endpoint/ApiEntityDao.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/endpoint/EndpointEnricher.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/endpoint/OperationNameBasedEndpointDiscoverer.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/endpoint/ApiEntityDaoTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/endpoint/EndpointEnricherTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/endpoint/OperationNameBasedEndpointDiscovererTest.java
Fixes https://github.com/hypertrace/hypertrace-ui/issues/1061
=> fix(endpoint-enricher): add service name to API entity

span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerResourceNormalizer.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanNormalizer.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanPreProcessor.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/TenantIdHandler.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/tenant/DefaultTenantIdProvider.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/tenant/JaegerKeyBasedTenantIdProvider.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/tenant/TenantIdProvider.java, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/jaeger/JaegerResourceNormalizerTest.java, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanPreProcessorTest.java
In hypertrace collector, we're going to remove tenantId from tags in span. Instead, tenantId will only be present in resource spans (refer [this PR](https://github.com/hypertrace/hypertrace-collector/pull/58)). So, we should be getting tenantId from `Process` in resource spans instead of getting from `Tags` in span. We're also keeping a fallback option for getting the tenantId from tags in span.
Updated unit test.
=> chore: read tenant id from process tags

semantic-convention-utils/build.gradle.kts
semantic-convention-utils is a module with utility functions and should have no dependency on any client
=> Removed unused entity service client dependency

hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/UserAgentSpanEnricher.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/UserAgentSpanEnricherTest.java
In case user agent length exceeds max length, the user agent is truncated to the configured max length
=> Enforce max length for user agent 

hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/UserAgentSpanEnricher.java
Added reporting of user agent cache metrics
=> Enabled reporting of user agent cache metrics

hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/EnrichmentProcessor.java, hypertrace-trace-enricher/hypertrace-trace-enricher/src/main/java/org/hypertrace/traceenricher/trace/enricher/StructuredTraceEnrichProcessor.java
We need enricher-wise metrics to identify the bottlenecks specific to enricher implementations.
Tested on a dev SaaS cluster
=> feat: Enricher wise metrics

hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/clients/DefaultClientRegistry.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/cache/EntityCache.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/DefaultServiceEntityEnricherTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/backend/BackendEntityEnricherTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/processor/StructuredTracesEnrichmentTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher/src/main/java/org/hypertrace/traceenricher/trace/enricher/StructuredTraceEnrichProcessor.java, hypertrace-trace-enricher/hypertrace-trace-enricher/src/main/java/org/hypertrace/traceenricher/trace/enricher/StructuredTraceEnricherConstants.java
- Added support for async cache loading in EntityCache
- Using the new async cache loading functionality in EdsCacheClient
=> Added support for async cache loading in EntityCache and EdsCacheClient

hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/ApiBoundaryTypeAttributeEnricher.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/ApiBoundaryTypeAttributeEnricherTest.java, semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/rpc/RpcSemanticConventionUtils.java, semantic-convention-utils/src/test/java/org/hypertrace/semantic/convention/utils/rpc/RpcSemanticConventionUtilsTest.java, span-normalizer/span-normalizer-constants/src/main/java/org/hypertrace/core/span/normalizer/constants/RpcSpanTag.java
Earlier host header was being checked through grpc authority. So it was suggested to check metadata host if authority was not present as a fallback. Added support for this.
=> fix : added fallback support for host headers 

semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/http/HttpSemanticConventionUtils.java
In some of the cases, the full URL was not visible on traces so added conditions to handle that.
=> trace url bug fix

hypertrace-view-generator/hypertrace-view-generator/src/main/java/org/hypertrace/viewgenerator/generators/SpanEventViewGenerator.java, hypertrace-view-generator/hypertrace-view-generator/src/test/java/org/hypertrace/viewgenerator/generators/SpanEventViewGeneratorTest.java
For RPC methods, we show URL/URI as a combination of `rpc.service` and `rpc.method`. The same information is also available as Span Name - https://github.com/open-telemetry/opentelemetry-specification/blob/3e380e249f60c3a5f68746f5e84d10195ba41a79/specification/trace/semantic_conventions/rpc.md#span-name
It has been observed that spanName is not correctly set on certain scenarios. However, the span contains `rpc.service` and `rpc.method` attribute correctly set. So, as part of this PR, we will first look into RPC attributes if a protocol is grpc, and if those are not present, we will fall back to eventName which is nothing but spanName.
Added unit tests
=> feat: add forming grpc reqeuest url if rpc attributes are present

hypertrace-view-generator/hypertrace-view-generator-api/src/main/avro/SpanEventView.avdl, hypertrace-view-generator/hypertrace-view-generator/src/main/java/org/hypertrace/viewgenerator/generators/SpanEventViewGenerator.java
Ref issue : https://github.com/hypertrace/hypertrace-ui/issues/1157
=> Addition of span count attribute

.snyk, hypertrace-metrics-exporter/hypertrace-metrics-exporter/build.gradle.kts, hypertrace-metrics-processor/hypertrace-metrics-processor/build.gradle.kts, hypertrace-trace-enricher/enriched-span-constants/build.gradle.kts, hypertrace-trace-enricher/enriched-span-constants/src/main/java/org/hypertrace/traceenricher/enrichedspan/constants/EnrichedSpanConstants.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/GrpcAttributeEnricher.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/GrpcAttributeEnricherTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/resources/enricher.conf, hypertrace-trace-enricher/hypertrace-trace-enricher/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher/src/main/resources/configs/common/application.conf, hypertrace-trace-enricher/trace-reader/build.gradle.kts, hypertrace-view-generator/hypertrace-view-generator/build.gradle.kts, hypertrace-view-generator/hypertrace-view-generator/src/main/java/org/hypertrace/viewgenerator/generators/SpanEventViewGenerator.java, hypertrace-view-generator/hypertrace-view-generator/src/test/java/org/hypertrace/viewgenerator/generators/SpanEventViewGeneratorTest.java, semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/http/HttpSemanticConventionUtils.java, semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/rpc/RpcSemanticConventionUtils.java, semantic-convention-utils/src/test/java/org/hypertrace/semantic/convention/utils/rpc/RpcSemanticConventionUtilsTest.java, span-normalizer/raw-span-constants/build.gradle.kts, span-normalizer/raw-span-constants/src/main/proto/org/hypertrace/core/span/constants/v1/span_attribute.proto, span-normalizer/span-normalizer-api/build.gradle.kts, span-normalizer/span-normalizer/build.gradle.kts
For RPC span, the span name is equivalent to Endpoint (URL) - https://github.com/open-telemetry/opentelemetry-specification/blob/3e380e249f60c3a5f68746f5e84d10195ba41a79/specification/trace/semantic_conventions/rpc.md#span-name
In cases if the convention is not followed, we would like to extend the platform to handle calc grpc request URL (& Endpoint) using a few other fallback attributes.
Secondly, we also want to enrich the URL based on client  (Sent) or server (Recv) calls.
So, This PR,
- add utility method for calc grpc request URL from spanName + fallback attributes
- add GrpcAttribute enricher which adds two new attributes 1) URL 2) Endpoint
- update spanEventView generator to use an enriched attribute for populating grpc request url
=> feat : add support for handling grpc request url

span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/SpanFilter.java, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanPreProcessorTest.java
Fixed the span drop criteria parsing logic which fails if the the tag value has the delimeter(`:`)
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally.
=> Fixed the span drop criteria parsing logic

.github/workflows/pr-build.yml
This PR, separate out `avroCompatibilityCheck` compatibility check into a different job.
This helps in certain scenarios where we first time adds avro file, and want to skip checks
=> refactor: moving out avro checks as a separate job

span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanPreProcessor.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/SpanDropFilter.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/SpanFilter.java, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/SpanNormalizerTest.java, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanPreProcessorTest.java, span-normalizer/span-normalizer/src/test/resources/configs/span-normalizer/application.conf
This PR, enhance the support for dropping the span at entry-level. There are certain issues in the existing one.
- It only supports equal operation
- it's not easily readable 
- uses a certain string delimiter making its error-prone
e.g of existing drop filter criteria
`["k1:v1, k2:v2", "k3:v3]`
As we can see, it is supported as an array of strings that are considered as OR expressions. The string supports AND operation via `:`.
New Approach:
- It will be readable JSON structure
- will supports EQ, CONTAINS, EXISTS and NEQ operator
e.g
```
[
[
{
"tagKey": "http.path",
"operator": "EQ",
"tagValue": "abcdef"
},
{
"tagKey": "http.url",
"operator": "CONTAINS",
"tagValue": "val"
},
{
"tagKey": "grpc.tag",
"operator": "EXISTS"
}
],
[
{
"tagKey": "tenant-id",
"operator": "EQ",
"tagValue": "xyz" …
```
=> feat: enhance the support for dropping filter

raw-spans-grouper/raw-spans-grouper/src/main/java/org/hypertrace/core/rawspansgrouper/RawSpanGrouperConstants.java, raw-spans-grouper/raw-spans-grouper/src/main/java/org/hypertrace/core/rawspansgrouper/RawSpansProcessor.java, raw-spans-grouper/raw-spans-grouper/src/test/java/org/hypertrace/core/rawspansgrouper/RawSpansGrouperTest.java, raw-spans-grouper/raw-spans-grouper/src/test/resources/configs/raw-spans-grouper/application.conf
The rawSpanGrouper, stitch the spans into traces. To cap the number of spans per tace, currently, we have config that controls per-tenant level. e.g
```
max.span.count = {
tenant1 = 5
}
```
As part of this PR, we are enhancing this scheme by adding a global upper limit.  As shown in the below example config, `tenant1` is applying 5 spans/trace limit, but for other tenants (say tenant2), it will apply 6 spans/trace limit.
```
default.max.span.count = 6
max.span.count = {
tenant1 = 5
}
```
=> feat: enhance the capping of max spans per trace at global level

raw-spans-grouper/helm/templates/raw-spans-grouper-config.yaml, raw-spans-grouper/helm/values.yaml, raw-spans-grouper/raw-spans-grouper/src/main/java/org/hypertrace/core/rawspansgrouper/RawSpansProcessor.java
As described as part of this PR (https://github.com/hypertrace/hypertrace-ingester/pull/290), we have added support for limiting trace size across all tenants.
This PR,
- expose the helm config for `default.max.span.count` 
- address the comments as suggested here of making the config as override than upper limit - https://github.com/hypertrace/hypertrace-ingester/pull/290#discussion_r756209776
=> fix: adds support for default max spans limit helm config

hypertrace-ingester/build.gradle.kts, hypertrace-ingester/src/main/java/org/hypertrace/ingester/HypertraceIngester.java, hypertrace-ingester/src/main/resources/configs/hypertrace-ingester/application.conf, hypertrace-metrics-exporter/hypertrace-metrics-exporter/src/main/resources/configs/common/application.conf, hypertrace-metrics-generator/hypertrace-metrics-generator/src/main/java/org/hypertrace/metrics/generator/MetricsGenerator.java, hypertrace-metrics-generator/hypertrace-metrics-generator/src/main/java/org/hypertrace/metrics/generator/MetricsProcessor.java, hypertrace-metrics-generator/hypertrace-metrics-generator/src/main/resources/configs/common/application.conf
As part of this ticket - https://github.com/hypertrace/hypertrace/issues/327 - on the context of providing application metrics support, this PR,
- adds all the newly added metrics pipeline components into hypertrace-ingester
- adds a flag for enabling and disabling it
- corresponding docker-compose PR - https://github.com/hypertrace/hypertrace/pull/328/
=> feat : add metrics pipeline components in hypertrace-ingester

hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/TraceStatsEnricherTest.java
Added a test case for TraceStatsEnricher to cover a specific scenario
=> Added test to cover scenario where there is a single ENTRY span in a trace

.snyk, hypertrace-ingester/build.gradle.kts, hypertrace-metrics-exporter/hypertrace-metrics-exporter/build.gradle.kts, hypertrace-metrics-generator/hypertrace-metrics-generator/build.gradle.kts, hypertrace-metrics-processor/hypertrace-metrics-processor/build.gradle.kts, hypertrace-trace-enricher/enriched-span-constants/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher-api/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-visualizer/build.gradle.kts, hypertrace-trace-enricher/trace-reader/build.gradle.kts, hypertrace-view-generator/hypertrace-view-creator/build.gradle.kts, hypertrace-view-generator/hypertrace-view-generator-api/build.gradle.kts, hypertrace-view-generator/hypertrace-view-generator/build.gradle.kts, raw-spans-grouper/raw-spans-grouper/build.gradle.kts, semantic-convention-utils/build.gradle.kts, span-normalizer/helm/templates/span-normalizer-config.yaml, span-normalizer/span-normalizer-api/build.gradle.kts, span-normalizer/span-normalizer/build.gradle.kts
This PR makes spanDropFilter configurable via helm tempale.
Tested locally by running `helm template ./helm`
Input into values.yaml file:
```
processor:
spanDropFilters: |-
[
[
{
"tagKey": "http.method",
"operator": "EQ",
"tagValue": "GET"
},
{
"tagKey": "http.url",
"operator": "CONTAINS",
"tagValue": "health"
}
],
[
{
"tagKey": "grpc.url",
"operator": "NEQ",
"tagValue": "Sent.TestServiceGetEchos"
}
]
]
```
Output:
```
apiVersion: v1
kind: ConfigMap
metadata:
name: span-normalizer-config
labels:
release: RELEASE-NAME
data:
application.conf: |-
kafka.streams.config {
application.id = jaeger-spans-to-raw-spans-job
<removed>
}
processor {
spanDropFilters = [
[
{
"tagKey": "http.method",
"operator": "EQ",
"tagValue": "GET"
},
{
"tagKey": "http.url",
"operator": "CONTAINS",
"tagValue": …
```
=> chore: extend the helm template for spanDropFilter

.snyk, hypertrace-metrics-generator/hypertrace-metrics-generator-api/build.gradle.kts, semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/http/HttpSemanticConventionUtils.java, semantic-convention-utils/src/test/java/org/hypertrace/semantic/convention/utils/http/HttpSemanticConventionUtilsTest.java, span-normalizer/raw-span-constants/build.gradle.kts, span-normalizer/span-normalizer-api/build.gradle.kts, span-normalizer/span-normalizer-constants/src/main/java/org/hypertrace/core/semantic/convention/constants/http/HttpSemanticConventions.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/fieldgenerators/HttpFieldsGenerator.java
In scenarios where a client connects to a LB/Proxy and a downstream server receives it the http.scheme span attribute will contain the protocol b/w the proxy and server and not the actual protocol b/w client and proxy. In such scenarios we should enrich the http.scheme attribute by first checking for presence of x-forwarded-proto and other forwarded headers and then proceed with the usual logic.
=> Extract protocol from x-forwarded-proto and other headers

span-normalizer/helm/templates/span-normalizer-config.yaml, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanPreProcessor.java, span-normalizer/span-normalizer/src/main/resources/configs/common/application.conf, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/SpanNormalizerTest.java, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanPreProcessorTest.java, span-normalizer/span-normalizer/src/test/resources/configs/span-normalizer/application.conf
There are cases when data received by the platform can be late. This can cause problems in an underlying store like pinot, etc.
In either case, we needed a configuration to drop late coming data.
As part of this PR, we are adding the below configuration at the span-normalizer component.
```
processor:
lateArrivalThresholdDuration: 5m
```
The above config tells that if the span's `start_time_millis` and span received time at `span-normalizer` is higher than 5m, it will be dropped.
- Added topology and unit tests
- Added helm config and tested locally by generating template
=> feat: add support for dropping late arrival data

span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/SpanFilter.java
As part of this PR,
- reducing the logging level to debug if we drop the span
- we already have dropped span counter for the same
=> chore: convert logging from info to debug message for span drop criteria

span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanPreProcessor.java
As part of my previous PR - https://github.com/hypertrace/hypertrace-ingester/pull/306, made the mistake of using the existing regular dropped counter map for registering new metrics for later arrival span.  This was causing the issue of not reporting metrics.
Fixing it as part of this PR.
=> fix: incorrect usage of metrics hashmap for late arrival counter

span-normalizer/helm/templates/span-normalizer-config.yaml, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanPreProcessor.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/TagsFilter.java, span-normalizer/span-normalizer/src/main/resources/configs/common/application.conf, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/SpanNormalizerTest.java, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanPreProcessorTest.java, span-normalizer/span-normalizer/src/test/resources/configs/span-normalizer/application.conf
There are cases that data-collection techniques used for collection can capture much more than required during the processing pipeline. And, we can't easily modify or control data collection module. So, based on request, as part of this PR, we are adding the configuration based functionality to drop un-used (or additional) tags as per need
The technique used here is that 
- identify the subset from which you want to drop or retain. This configuration can be provided using `allowed.attributes.prefixes`
- Provide the list of attribute keys that you won't retain for the subset of keys. This can be provided using `prefixed.matched.allowed.attributes`
As an example, I want to retain `x-allowed-1` attributes from all extension attributes of http request header.
So, in this case, we can …
=> feat: adds support for filtering of un-used tags

hypertrace-ingester/src/test/java/org/hypertrace/migration/MigrationTestHttp.java, hypertrace-ingester/src/test/java/org/hypertrace/migration/MigrationTestRpc.java, hypertrace-trace-enricher/enriched-span-constants/src/main/java/org/hypertrace/traceenricher/enrichedspan/constants/utils/EnrichedSpanUtils.java, semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/http/HttpSemanticConventionUtils.java, span-normalizer/span-normalizer/build.gradle.kts, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/ExcludeSpanRuleEvaluator.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanNormalizer.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanPreProcessor.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanToAvroRawSpanTransformer.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/PreProcessedSpan.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/SpanDropManager.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/util/EventBuilder.java, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanNormalizerTest.java, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanPreProcessorTest.java, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanToLogRecordsTransformerTest.java
This PR makes one major change in adding `Event` to `PreprocessedSpan`. The reason being the following:
We observed that the dropping of spans  via Exclude span rules was not working on few of the spans.  The reason for this is as follows. There are different ways in which the full url can be constructed from the span using the various attributes. It could either be available directly under some span attribute(say like `http.url`) or would have to be constructed from multiple such attributes(like in OTel format, construct from `http.scheme`, `http.host` and `http.target`). We have a method called `getFullHttpUrl` which takes into account all the factors and builds the full http url. However, it takes in `Event` object and constructs it. 
To make use of this method in span exclusion using …
=> Drop spans based on event

hypertrace-ingester/build.gradle.kts, hypertrace-metrics-generator/hypertrace-metrics-generator/build.gradle.kts, hypertrace-metrics-processor/hypertrace-metrics-processor/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher/src/main/java/org/hypertrace/traceenricher/trace/enricher/StructuredTraceEnrichProcessor.java, hypertrace-trace-enricher/hypertrace-trace-enricher/src/main/java/org/hypertrace/traceenricher/trace/enricher/TraceEnricher.java, hypertrace-trace-enricher/hypertrace-trace-enricher/src/test/java/HypertraceTraceEnricherTest.java, raw-spans-grouper/raw-spans-grouper/build.gradle.kts, raw-spans-grouper/raw-spans-grouper/src/main/java/org/hypertrace/core/rawspansgrouper/RawSpansGrouper.java, raw-spans-grouper/raw-spans-grouper/src/main/java/org/hypertrace/core/rawspansgrouper/RawSpansProcessor.java, raw-spans-grouper/raw-spans-grouper/src/main/java/org/hypertrace/core/rawspansgrouper/TraceEmitPunctuator.java, raw-spans-grouper/raw-spans-grouper/src/test/java/org/hypertrace/core/rawspansgrouper/RawSpansGrouperTest.java, span-normalizer/span-normalizer/build.gradle.kts
grouper produces keyed output
enricher produces keyed input
Unit tests
NA
=> grouper/enricher produces/consumes keyed input

settings.gradle.kts
Running gradlew projects command will display all the project names to verify.
=> change root project name to avoid duplicate project names. 

hypertrace-ingester/build.gradle.kts, hypertrace-trace-enricher/enriched-span-constants/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher-api/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-enricher/build.gradle.kts, hypertrace-trace-enricher/hypertrace-trace-visualizer/build.gradle.kts, hypertrace-trace-enricher/trace-reader/build.gradle.kts, hypertrace-view-generator/hypertrace-view-generator-api/build.gradle.kts, hypertrace-view-generator/hypertrace-view-generator/build.gradle.kts, raw-spans-grouper/raw-spans-grouper/build.gradle.kts, semantic-convention-utils/build.gradle.kts
data-model version and avro version were upgraded in [this PR](https://github.com/hypertrace/hypertrace-ingester/pull/332/files#diff-fc460f912c3e92b13013deb0ec2660eaf7c49471037b56face890f8080d17ae1R60) in span-normalizer only. This PR makes similar changes in the rest of the modules.
=> chore: upgrade data-model and avro version

semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/http/HttpSemanticConventionUtils.java, semantic-convention-utils/src/test/java/org/hypertrace/semantic/convention/utils/http/HttpSemanticConventionUtilsTest.java, span-normalizer/span-normalizer-constants/src/main/java/org/hypertrace/core/semantic/convention/constants/http/HttpSemanticConventions.java
This change introduces 2 changes:
1. If a full http url is present and the scheme is 'http' then other attributes are considered to extract scheme and checked if any of them have 'https'. If any of them have 'https' then we use that as the scheme. Ex: if http.url = http://foo.com and x-forwarded-proto = https or origin = https://foo.com then the resolved scheme will be 'https'. This scenario can happen if there is a frontend load balancer that terminates SSL traffic.
2. Add support for extracting scheme from http origin request header
Added unit tests
=> Add support to look for http scheme from origin header

hypertrace-ingester/build.gradle.kts, hypertrace-view-generator/hypertrace-view-creator/build.gradle.kts, hypertrace-view-generator/hypertrace-view-generator/build.gradle.kts
Upgrading view-gen libs, the prior version was causing test case failure on - https://github.com/hypertrace/query-service/pull/174, which had deps on `main` tag image on `view-generation`. As the latest version of view-generation-framework revet the pinot client libs, this PR will help fixing the above - https://github.com/hypertrace/query-service/runs/8154986276?check_suite_focus=true
=> chore: upgrade view generation and creation framework libs

hypertrace-view-generator/hypertrace-view-generator/build.gradle.kts
The dependent test case are still failing - https://github.com/hypertrace/query-service/runs/8187425254?check_suite_focus=true 
```
worker.jar:?]
2022-09-05 11:27:00.556 [Test worker] ERROR 🐳 [hypertrace/hypertrace-view-generator:main] - Log output from the failed container:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-09-05 11:27:00.557 [Test worker] INFO  🐳 [hypertrace/hypertrace-view-generator:main] - Creating container for image: hypertrace/hypertrace-view-generator:main
2022-09-05 11:27:00.632 [Test worker] INFO  🐳 [hypertrace/hypertrace-view-generator:main] - Starting container with ID: …
```
=> chore: adds sl4j impl lib for runtime

span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/SpanDropFilter.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/SpanFilter.java, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/SpanNormalizerTest.java, span-normalizer/span-normalizer/src/test/resources/configs/span-normalizer/application.conf
This PR,
- adds support for span drop filter criteria for operation ame
- adds exits/not_exits operator
=> enhanced the span drop filter for operation name

semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/http/HttpSemanticConventionUtils.java, semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/span/SpanSemanticConventionUtils.java, semantic-convention-utils/src/test/java/org/hypertrace/semantic/convention/utils/db/DbSemanticConventionUtilsTest.java, semantic-convention-utils/src/test/java/org/hypertrace/semantic/convention/utils/http/HttpSemanticConventionUtilsTest.java, semantic-convention-utils/src/test/java/org/hypertrace/semantic/convention/utils/span/SpanSemanticConventionUtilsTest.java, span-normalizer/span-normalizer-constants/src/main/java/org/hypertrace/core/semantic/convention/constants/span/OTelSpanSemanticConventions.java
net.peer.ip has been renamed to net.sock.peer.addr. See changelog:
[opentelemetry-specification/CHANGELOG.md at ac639af144fbb3875af921d5ba30ad04417564de · open-telemetry/opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/blob/ac639af144fbb3875af921d5ba30ad04417564de/CHANGELOG.md)
Made changes to support the new net.sock.peer.addr tag
=> Added support for the new OTEL net.sock.peer.addr attribute

hypertrace-ingester/src/test/java/org/hypertrace/migration/MigrationTestHttp.java, hypertrace-ingester/src/test/java/org/hypertrace/migration/MigrationTestRpc.java, span-normalizer/helm/templates/span-normalizer-config.yaml, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanNormalizer.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanPreProcessor.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/ServiceNamer.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/util/EventBuilder.java, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanNormalizerTest.java, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanToLogRecordsTransformerTest.java, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/jaeger/ServiceNamerTest.java
Separated the service naming evaluation to new class, and added the ability for a config-driven list of attributes to check for a service name before using the resource service name, and then finally, if both the override and resource name are empty, a fallback list to check.
Added unit tests
=> feat: add ability to configure a preferred service name attr

raw-spans-grouper/helm/templates/headless-service.yaml, raw-spans-grouper/helm/templates/logconfig.yaml, raw-spans-grouper/helm/templates/raw-spans-grouper-config.yaml, raw-spans-grouper/helm/templates/statefulset.yaml, raw-spans-grouper/helm/values.yaml, span-normalizer/helm/templates/deployment.yaml, span-normalizer/helm/templates/hpa.yaml, span-normalizer/helm/templates/logconfig.yaml, span-normalizer/helm/values.yaml
Wrapping the charts of span-normalizer and raw-spans-grouper under charType, so it can be used as library charts as dependency.
Locally ran the helm template. No change in current vs Prior.
=> adding support of using charts as library for certain components

hypertrace-trace-enricher/helm/templates/trace-enricher-config.yaml, hypertrace-trace-enricher/helm/values.yaml, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/clients/ClientRegistry.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/clients/DefaultClientRegistry.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/UserAgentSpanEnricher.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/util/UserAgentParser.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/test/java/org/hypertrace/traceenricher/enrichment/enrichers/UserAgentSpanEnricherTest.java, hypertrace-trace-enricher/hypertrace-trace-enricher/src/main/resources/configs/common/application.conf, hypertrace-trace-enricher/hypertrace-trace-enricher/src/test/resources/configs/hypertrace-trace-enricher/application.conf
Change user agent caching strategy to not refresh (because the value is static) and evict based on access rather than origin.
Also moved user agent parser into standalone class with its own cache so it can be shared across stream threads (unlike the enrichers).
=> refactor: fix expiration of ua cache

.github/workflows/pr-build.yml
To fix: https://github.com/hypertrace/hypertrace-ingester/actions/runs/5452280343/jobs/9919573254?pr=396
=> chore: add category info to fix trivy build issue

semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/http/HttpSemanticConventionUtils.java, semantic-convention-utils/src/test/java/org/hypertrace/semantic/convention/utils/http/HttpSemanticConventionUtilsTest.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/ExcludeSpanRuleEvaluator.java, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/SpanDropManager.java
This PR updates the logic of building the full url to make port optional. It also updates the exclusion rule url filter eval to use url path as fallback in case the full url does not exist.
Added unit tests
=> make port optional to build full url, exclusion rule eval fallback on url path

hypertrace-trace-enricher/trace-reader/src/main/java/org/hypertrace/trace/accessor/entities/DefaultTraceEntityAccessor.java
Let the rxjava call run in the same thread. With async, it will run in threads part of async executor pool.
=> chore: remove subscribeOn on a scheduler

gradle/libs.versions.toml, hypertrace-trace-enricher/hypertrace-trace-enricher-api/src/main/java/org/hypertrace/traceenricher/trace/util/StructuredTraceGraphBuilder.java
=> chore | remove entities in structured trace graph

owasp-suppressions.xml, semantic-convention-utils/src/main/java/org/hypertrace/semantic/convention/utils/http/HttpSemanticConventionUtils.java
=> Move logs to debug

.github/workflows/hypertrace-ingester/docker-compose.yml, .github/workflows/hypertrace-ingester/postgres/docker-compose.yml, owasp-suppressions.xml, span-normalizer/helm/templates/span-normalizer-config.yaml, span-normalizer/span-normalizer/src/test/resources/configs/span-normalizer/application.conf
=> fix: bypass.override.tenants config to be non quoted

gradle/libs.versions.toml, span-normalizer/span-normalizer/src/main/java/org/hypertrace/core/spannormalizer/jaeger/ExcludeSpanRuleEvaluator.java, span-normalizer/span-normalizer/src/test/java/org/hypertrace/core/spannormalizer/jaeger/JaegerSpanPreProcessorTest.java
=> Consume URL_PATH and evaluate according for span exclusion

hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/cache/EntityCache.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/space/SpaceRulesCachingClient.java, hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/util/UserAgentParser.java, owasp-suppressions.xml
- Prefixing the class name as part of entity cache
- Reference PR: https://github.com/hypertrace/hypertrace-ingester/pull/453/files
=> chore: fixed the naming of entity cache
